site_name: SL10n Docs

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ sl10n ]
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Welcome!: index.md
  - Quick Start: quick-start.md
  - API Reference: reference.md