site_name: SL10n Docs
repo_url: https://github.com/SyberiaK/sl10n
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.integrate

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ sl10n ]
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            merge_init_into_class: yes
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - index.md
  - quick-start.md
  - reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SyberiaK
      name: SyberiaK on GitHub
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/syberiakey
      name: SyberiaK on Twitter (screw you Elon)