name: Publish docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up project
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Saving cache_id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
          pip install mkdocstrings
          pip install mkdocstrings-python
          pip install mkdocs-material
      - name: Publish docs
        run: mkdocs gh-deploy --force