name: Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up project
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Saving cache_id, step 1
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Saving cache_id, step 2
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_docs.txt
      - name: Publish docs
        run: mkdocs gh-deploy --force